# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(729, 300)
        self.LoadImage1 = QtWidgets.QPushButton(Dialog)
        self.LoadImage1.setGeometry(QtCore.QRect(20, 40, 101, 28))
        self.LoadImage1.setObjectName("LoadImage1")
        self.LoadImage2 = QtWidgets.QPushButton(Dialog)
        self.LoadImage2.setGeometry(QtCore.QRect(20, 160, 101, 28))
        self.LoadImage2.setObjectName("LoadImage2")
        self.Path1 = QtWidgets.QLabel(Dialog)
        self.Path1.setGeometry(QtCore.QRect(30, 90, 181, 16))
        self.Path1.setObjectName("Path1")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 30, 160, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ProcessverticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ProcessverticalLayout.setContentsMargins(0, 0, 0, 0)
        self.ProcessverticalLayout.setObjectName("ProcessverticalLayout")
        self.ColorSeparation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ColorSeparation.setObjectName("ColorSeparation")
        self.ProcessverticalLayout.addWidget(self.ColorSeparation)
        self.ColorTransform = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ColorTransform.setObjectName("ColorTransform")
        self.ProcessverticalLayout.addWidget(self.ColorTransform)
        self.ColorDetection = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ColorDetection.setObjectName("ColorDetection")
        self.ProcessverticalLayout.addWidget(self.ColorDetection)
        self.Blending = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Blending.setObjectName("Blending")
        self.ProcessverticalLayout.addWidget(self.Blending)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(490, 30, 160, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.SmoothverticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.SmoothverticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.SmoothverticalLayout_2.setObjectName("SmoothverticalLayout_2")
        self.GaussianBlur = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.GaussianBlur.setObjectName("GaussianBlur")
        self.SmoothverticalLayout_2.addWidget(self.GaussianBlur)
        self.BilateralFilter = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.BilateralFilter.setObjectName("BilateralFilter")
        self.SmoothverticalLayout_2.addWidget(self.BilateralFilter)
        self.MedianFilter = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MedianFilter.setObjectName("MedianFilter")
        self.SmoothverticalLayout_2.addWidget(self.MedianFilter)
        self.ImageProcessing = QtWidgets.QLabel(Dialog)
        self.ImageProcessing.setGeometry(QtCore.QRect(220, 10, 151, 16))
        self.ImageProcessing.setObjectName("ImageProcessing")
        self.ImageSmoothing = QtWidgets.QLabel(Dialog)
        self.ImageSmoothing.setGeometry(QtCore.QRect(490, 10, 151, 16))
        self.ImageSmoothing.setObjectName("ImageSmoothing")
        self.Path2 = QtWidgets.QLabel(Dialog)
        self.Path2.setGeometry(QtCore.QRect(30, 210, 181, 16))
        self.Path2.setObjectName("Path2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LoadImage1.setText(_translate("Dialog", "Load Image 1"))
        self.LoadImage2.setText(_translate("Dialog", "Load Image 2"))
        self.Path1.setText(_translate("Dialog", "path"))
        self.ColorSeparation.setText(_translate("Dialog", "1.1 Color Separation"))
        self.ColorTransform.setText(_translate("Dialog", "1.2 Color Transformation"))
        self.ColorDetection.setText(_translate("Dialog", "1.3 Color Detection"))
        self.Blending.setText(_translate("Dialog", "1.4 Blending"))
        self.GaussianBlur.setText(_translate("Dialog", "2.1 Gaussian Blur"))
        self.BilateralFilter.setText(_translate("Dialog", "2.2 Bilateral filter"))
        self.MedianFilter.setText(_translate("Dialog", "2.3 Median filter"))
        self.ImageProcessing.setText(_translate("Dialog", "1. Image Processing"))
        self.ImageSmoothing.setText(_translate("Dialog", "2. Image Smoothing"))
        self.Path2.setText(_translate("Dialog", "path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
