# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 300)
        self.LoadImage = QtWidgets.QPushButton(Dialog)
        self.LoadImage.setGeometry(QtCore.QRect(20, 120, 111, 31))
        self.LoadImage.setObjectName("LoadImage")
        self.Path = QtWidgets.QLabel(Dialog)
        self.Path.setGeometry(QtCore.QRect(20, 180, 101, 16))
        self.Path.setObjectName("Path")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 40, 160, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GaussianBlur = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.GaussianBlur.setObjectName("GaussianBlur")
        self.verticalLayout.addWidget(self.GaussianBlur)
        self.SobelX = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SobelX.setObjectName("SobelX")
        self.verticalLayout.addWidget(self.SobelX)
        self.SobelY = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SobelY.setObjectName("SobelY")
        self.verticalLayout.addWidget(self.SobelY)
        self.Magnitude = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Magnitude.setObjectName("Magnitude")
        self.verticalLayout.addWidget(self.Magnitude)
        self.EdgeDetection = QtWidgets.QLabel(Dialog)
        self.EdgeDetection.setGeometry(QtCore.QRect(150, 10, 141, 31))
        self.EdgeDetection.setObjectName("EdgeDetection")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 40, 160, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Resize = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Resize.setObjectName("Resize")
        self.verticalLayout_2.addWidget(self.Resize)
        self.Translation = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Translation.setObjectName("Translation")
        self.verticalLayout_2.addWidget(self.Translation)
        self.RotationScaling = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.RotationScaling.setObjectName("RotationScaling")
        self.verticalLayout_2.addWidget(self.RotationScaling)
        self.Shearing = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Shearing.setObjectName("Shearing")
        self.verticalLayout_2.addWidget(self.Shearing)
        self.Transformation = QtWidgets.QLabel(Dialog)
        self.Transformation.setGeometry(QtCore.QRect(380, 20, 151, 16))
        self.Transformation.setObjectName("Transformation")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LoadImage.setText(_translate("Dialog", "Load Image"))
        self.Path.setText(_translate("Dialog", "path"))
        self.GaussianBlur.setText(_translate("Dialog", "3.1 Gaussian Blur"))
        self.SobelX.setText(_translate("Dialog", "3.2 Sobel X"))
        self.SobelY.setText(_translate("Dialog", "3.3 Sobel Y"))
        self.Magnitude.setText(_translate("Dialog", "3.4 Magnitude"))
        self.EdgeDetection.setText(_translate("Dialog", "3. Edge Detection"))
        self.Resize.setText(_translate("Dialog", "4.1 Resize"))
        self.Translation.setText(_translate("Dialog", "4.2 Translation"))
        self.RotationScaling.setText(_translate("Dialog", "4.3 Rotation, Scaling"))
        self.Shearing.setText(_translate("Dialog", "4.4 Shearing"))
        self.Transformation.setText(_translate("Dialog", "4. Transformation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
